### ISSUE TITLE
Use any-promise instead of native-or-bluebird

### ISSUE THREAD

**Issue by RangerMauve** [yoshuawuyts/promise-filter#2]
[any-promise](https://npmjs.org/package/any-promise) supports a variety of other promise libraries as well so it'd mean one would be able to use a lighter promise implementation if size is an issue.

**Comment by yoshuawuyts** [comment]
Oh, that's an excellent suggestion.

**Comment by yoshuawuyts** [comment]
Added in e91b3656626105109882316d9f824a1479047b22 :tada:

**Comment by RangerMauve** [comment]
Awesome, thanks!
